### ISSUE TITLE
Adding Pushbullet and ability to set defaults.

### ISSUE THREAD

**Issue by vikjam** [wschpero/statapush#2]
I don't mean to inundate you with issues, but in the development branch ([develop](https://github.com/vikjam/statapush/tree/develop)) of my fork, I added support Pushbullet and the ability to save user IDs and tokens so you don't have include them each time when you `statapush`. I documented it in the [README](https://github.com/vikjam/statapush/tree/develop) from the development branch of the fork. No pressure to include them in your version--I just found these features helpful for myself! You can install the development branch similarly:

``` stata
net install statapush,  from("https://raw.github.com/vikjam/statapush/develop/") replace
```

If you think these are worthwhile to merge too, I can clean up the code and documentation in a pull request.

**Comment by wschpero** [comment]
Hi!

This is another wonderful addition. Apologies for not responding sooner on your original issue - I've been a bit swamped. I promise I will take a look in the next couple of days and will get back to you by the end of the week (at the latest) with some solid next steps.

Thanks again!

Will

**Comment by vikjam** [comment]
No problem! I'm probably going to be a bit busy this week, but I look forward to hearing your thoughts whenever I get a chance to take a look at this again.

Thanks for putting this out there!

**Comment by wschpero** [comment]
Hi!

I took a look at your additions and I think they're great. I'd love to incorporate them into the production release (and submit an updated version to the SSC Archive). A few thoughts on some next steps:

**1. Submit a pull request**: Once you've had a chance to look over your code, feel free to submit a pull request. Two notes before you do so:

**1.a. Error reporting**: I don't think the error reporting function is working properly. I can't seem to trigger your code to push notification of the error instead of the specified message when an error is detected.

**1.b. Provider preference**: I think it's worth having statapush and statapushpref throw out an error if you don't specify one of the two provider options correctly (e.g., misspell "pushbullet").

**2. Updating documentation (help file, readme)**: I'm happy to take care of this once you submit the pull request for the two .ado files. There are some weird formatting idiosyncrasies that affect how the help file is displayed in Stata 12/13 vs. 14. 

**3. Authorship**: Given your contributions, I'd love you add your name as an author. If you're comfortable with me doing so, feel free to send me your name via email.

Please let me know what you think of the above! I'm going to close your first issue and we can continue conversation here if necessary.

Best,
Will

**Comment by wschpero** [comment]
Sorry - two other notes:
1. I think we should design the package so that users will always first save their user information / provider preferences via statapushpref (with all three arguments required) and then simply specify their message via statapush (which they could employ with or without "using"). I can't imagine a use case where this would not be preferred. As a result, I don't the user-facing syntax for statapush should have any arguments beyond message() (required) and using"" (optional). What do you think?
2. Given users don't have to enclose their user information / message within quotes, I don't think we should require them to include their provider pref in quotes either. Just to be consistent - should be pretty easy to implement.

Best,
Will

**Comment by wschpero** [comment]
And I should mention I'm happy to take a first shot at implementing the above. Let me know how you would prefer to move forward. You could certainly submit a pull request with what you have now and then I can work from that.

Will

**Comment by vikjam** [comment]
On point **1a**, looks like I had a typo in the example, there should be a newline after the regression (otherwise Stata doesn't run that line, which means no error will be thrown in the example).

```
* Install fork
net install statapush, from("https://raw.github.com/vikjam/statapush/master/") replace

* Create an example do file that has an error
file open example using "example-do.do", write
file write example "sysuse auto.dta" _n "regressx mpg price" _n
file close example

* Run statapush
statapush using "example-do.do", token(<INSERT API TOKEN>) userid(<INSERT USER KEY>) message(<INSERT MESSAGE>)
```

I agree on **1b**. I'll add error checking and I was thinking we could even make the provider lowercase using the string function `lower`.

**2**. Your help with that would be great. The formatting on Stata help files mystifies me...

**3**. Aww shucks, I appreciate that! 

As for requiring people to set their preferences, I wasn't sure if people who used a shared Stata .ado library would want to store their preferences since they could conflict.

I think you should be able to pass the provider without quotes--I'll change the example to reflect that.

**Comment by wschpero** [comment]
Good point on setting preferences. Agreed. Would you prefer to submit separate pull requests for the error handling function and the storing preferences / pushbullet contributions? Or just one with everything?
